### ISSUE TITLE
AccessViolationException errors

### ISSUE THREAD

**Issue by markrendle** [txdv/LibuvSharp#7]
I'm working on a version of my Flux web server using LibuvSharp: https://github.com/markrendle/flux/tree/libuv

My test console application works fine until I hit it with around 10,000 requests using `weighttp -n 10000 -t 4 -c 8`, at which point I start getting AccessViolationException thrown all over the place.

It also gets thrown sometimes when running the `TcpFixture.Stress` test (using R# test runner).

This is on a fairly monster PC, overclocked i7-4770, 32GB RAM, SSDs, etc.

I'm going to do some investigation of my own today, but thought I'd open an issue to get other eyes on the problem.

**Comment by txdv** [comment]
@terender suggestion seems reasonable.

On mono these 'on the fly' delegates on static methods are actually saved forever. On the .NET framework they are not. My assumption they would stay, but I have fixed it in a commit that I have locally.
